import { FormEvent, useEffect, useMemo, useState } from 'react'
import { collection, doc, getDoc, getDocs, serverTimestamp, setDoc } from 'firebase/firestore'
import { firebaseAuth, firestoreDb } from './firebase'
import type { User } from './types'

type Props={user:User}
type Row={id:string;actualReportId:string;date:string;monthKey:string;shift:string;sourceType:string;dailyLinkStatus:string;monthlyLinkStatus:string;dailyPlanId:string;monthlyPlanLineId:string;dailySourcePlanIdRaw:string;monthlyLegacyPlanId:string;companyCode:string;farm:string;pid:string;paddockRaw:string;activity:string;actualAreaHa:number;plannedDailyAreaHa:number;dailyVarianceHa:number;manpower:number;unitName:string;foreman:string;notes:string;masterPending:boolean}
type DailyRef={id:string;dailyPlanId:string;date:string;shift:string;sourceType:string;monthlyPlanLineId:string;companyCode:string;farm:string;pid:string;activity:string;description:string;areaHa:number}
type Log={id:string;sourceFileName:string;total:number;created:number;updated:number;unchanged:number;protected:number;dailyLinked:number;dailyPending:number;monthlyLinked:number;masterPending:number;warnings:number;errors:number;importedBy:string;importedAt:string}
function text(v:unknown){return v===null||v===undefined?'':String(v).trim()}
function num(v:unknown){const n=Number(v||0);return Number.isFinite(n)?n:0}
function dt(v:unknown){if(!v)return'';if(typeof v==='string')return v;if(typeof v==='object'&&v!==null&&'toDate'in v&&typeof(v as {toDate?:unknown}).toDate==='function'){try{return(v as {toDate:()=>Date}).toDate().toISOString()}catch{return''}}return''}
function row(id:string,d:Record<string,unknown>):Row{return{id,actualReportId:text(d.actualReportId||id),date:text(d.date),monthKey:text(d.monthKey),shift:text(d.shift),sourceType:text(d.sourceType),dailyLinkStatus:text(d.dailyLinkStatus),monthlyLinkStatus:text(d.monthlyLinkStatus),dailyPlanId:text(d.dailyPlanId),monthlyPlanLineId:text(d.monthlyPlanLineId),dailySourcePlanIdRaw:text(d.dailySourcePlanIdRaw),monthlyLegacyPlanId:text(d.monthlyLegacyPlanId),companyCode:text(d.companyCode),farm:text(d.farm),pid:text(d.pid),paddockRaw:text(d.paddockRaw),activity:text(d.activity),actualAreaHa:num(d.actualAreaHa),plannedDailyAreaHa:num(d.plannedDailyAreaHa),dailyVarianceHa:num(d.dailyVarianceHa),manpower:num(d.manpower),unitName:text(d.unitName),foreman:text(d.foreman),notes:text(d.notes),masterPending:d.masterPending===true}}
function dailyRef(id:string,d:Record<string,unknown>):DailyRef{return{id,dailyPlanId:text(d.dailyPlanId||id),date:text(d.date),shift:text(d.shift),sourceType:text(d.sourceType),monthlyPlanLineId:text(d.monthlyPlanLineId),companyCode:text(d.companyCode),farm:text(d.farm),pid:text(d.pid),activity:text(d.activity),description:text(d.description),areaHa:num(d.areaHa)}}
function log(id:string,d:Record<string,unknown>):Log{return{id,sourceFileName:text(d.sourceFileName),total:num(d.total),created:num(d.created),updated:num(d.updated),unchanged:num(d.unchanged),protected:num(d.protected),dailyLinked:num(d.dailyLinked),dailyPending:num(d.dailyPending),monthlyLinked:num(d.monthlyLinked),masterPending:num(d.masterPending),warnings:num(d.warnings),errors:num(d.errors),importedBy:text(d.importedBy),importedAt:dt(d.importedAt)}}
function ha(v:number){return new Intl.NumberFormat('id-ID',{minimumFractionDigits:2,maximumFractionDigits:2}).format(v)+' Ha'}
function date(v:string){if(!v)return'-';const d=new Date(v+'T00:00:00');return Number.isNaN(d.getTime())?v:d.toLocaleDateString('id-ID')}
function dateTime(v:string){if(!v)return'-';const d=new Date(v);return Number.isNaN(d.getTime())?v:d.toLocaleString('id-ID')}
async function writerContext(appUser:User){const db=firestoreDb,auth=firebaseAuth;if(!db||!auth)throw new Error('Firebase belum tersedia.');const current=auth.currentUser;if(!current)throw new Error('Login Firebase tidak tersedia.');const snap=await getDoc(doc(db,'users',current.uid));if(!snap.exists())throw new Error('Profil user tidak ditemukan.');const p=snap.data() as Record<string,unknown>;if(p.active!==true||!['owner','asisten'].includes(text(p.role))||!['owner','asisten'].includes(appUser.role))throw new Error('Role tidak memiliki izin edit Actual Plan.');return{db,username:text(p.username)||appUser.username}}

export default function ActualPlanListPanel({user}:Props){
  const[rows,setRows]=useState<Row[]>([]),[daily,setDaily]=useState<DailyRef[]>([]),[logs,setLogs]=useState<Log[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState('')
  const[month,setMonth]=useState('ALL'),[source,setSource]=useState('ALL'),[link,setLink]=useState('ALL'),[company,setCompany]=useState('ALL'),[farm,setFarm]=useState('ALL'),[activity,setActivity]=useState('ALL'),[query,setQuery]=useState('')
  const[editingId,setEditingId]=useState(''),[editDate,setEditDate]=useState(''),[editArea,setEditArea]=useState(''),[editManpower,setEditManpower]=useState(''),[editUnit,setEditUnit]=useState(''),[editForeman,setEditForeman]=useState(''),[editNotes,setEditNotes]=useState(''),[editDaily,setEditDaily]=useState(''),[dailyQuery,setDailyQuery]=useState('')

  async function load(){if(!firestoreDb){setMessage('Firestore belum tersedia.');return}setBusy(true);try{const[a,d,b]=await Promise.all([getDocs(collection(firestoreDb,'daily_reports')),getDocs(collection(firestoreDb,'daily_plans')),getDocs(collection(firestoreDb,'actual_plan_import_logs'))]);const rr=a.docs.map(x=>row(x.id,x.data() as Record<string,unknown>)).sort((x,y)=>y.date.localeCompare(x.date)||x.pid.localeCompare(y.pid,undefined,{numeric:true}));const dd=d.docs.map(x=>dailyRef(x.id,x.data() as Record<string,unknown>)).sort((x,y)=>y.date.localeCompare(x.date)||x.dailyPlanId.localeCompare(y.dailyPlanId));const ll=b.docs.map(x=>log(x.id,x.data() as Record<string,unknown>)).sort((x,y)=>y.importedAt.localeCompare(x.importedAt)).slice(0,10);setRows(rr);setDaily(dd);setLogs(ll);setMessage('Actual Plan siap: '+rr.length+' record. Klik Edit untuk koreksi actual atau memperbaiki link Daily Plan.')}catch(e){setMessage(e instanceof Error?e.message:'Actual Plan gagal dimuat.')}finally{setBusy(false)}}
  useEffect(()=>{void load()},[])
  const months=useMemo(()=>[...new Set(rows.map(x=>x.monthKey).filter(Boolean))].sort().reverse(),[rows]),companies=useMemo(()=>[...new Set(rows.map(x=>x.companyCode).filter(Boolean))].sort(),[rows]),farms=useMemo(()=>[...new Set(rows.filter(x=>company==='ALL'||x.companyCode===company).map(x=>x.farm).filter(Boolean))].sort(),[rows,company]),activities=useMemo(()=>[...new Set(rows.map(x=>x.activity).filter(Boolean))].sort(),[rows])
  const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return rows.filter(r=>(month==='ALL'||r.monthKey===month)&&(source==='ALL'||r.sourceType===source)&&(link==='ALL'||r.dailyLinkStatus===link)&&(company==='ALL'||r.companyCode===company)&&(farm==='ALL'||r.farm===farm)&&(activity==='ALL'||r.activity===activity)&&(!q||[r.actualReportId,r.dailySourcePlanIdRaw,r.monthlyLegacyPlanId,r.dailyPlanId,r.monthlyPlanLineId,r.pid,r.paddockRaw,r.activity,r.foreman,r.unitName,r.notes].join(' ').toLowerCase().includes(q)))},[rows,month,source,link,company,farm,activity,query])
  const totals=useMemo(()=>filtered.reduce((a,r)=>({area:a.area+r.actualAreaHa,man:a.man+r.manpower,linked:a.linked+(r.dailyLinkStatus==='LINKED'?1:0),pending:a.pending+(r.dailyLinkStatus!=='LINKED'?1:0)}),{area:0,man:0,linked:0,pending:0}),[filtered])
  const editing=rows.find(x=>x.id===editingId)||null
  const dailyChoices=useMemo(()=>{const q=dailyQuery.trim().toLowerCase();return daily.filter(x=>!q||[x.dailyPlanId,x.monthlyPlanLineId,x.date,x.pid,x.activity,x.description,x.companyCode,x.farm].join(' ').toLowerCase().includes(q)).slice(0,400)},[daily,dailyQuery])
  const selectedDaily=daily.find(x=>x.dailyPlanId===editDaily)||null
  const editContext=editing?{
    paddock:selectedDaily?.pid||editing.pid,
    shift:selectedDaily?.shift||editing.shift,
    activity:selectedDaily?.activity||editing.activity,
    monthlyPlanLineId:selectedDaily?.monthlyPlanLineId||editing.monthlyPlanLineId,
    companyCode:selectedDaily?.companyCode||editing.companyCode,
    farm:selectedDaily?.farm||editing.farm,
    plannedAreaHa:selectedDaily?.areaHa||editing.plannedDailyAreaHa
  }:null

  function startEdit(r:Row){setEditingId(r.id);setEditDate(r.date);setEditArea(String(r.actualAreaHa));setEditManpower(String(r.manpower));setEditUnit(r.unitName);setEditForeman(r.foreman);setEditNotes(r.notes);setEditDaily(r.dailyPlanId);setDailyQuery('');requestAnimationFrame(()=>document.getElementById('actual-edit-panel')?.scrollIntoView({behavior:'smooth',block:'start'}))}
  function cancelEdit(){setEditingId('');setDailyQuery('')}
  async function saveEdit(e:FormEvent){e.preventDefault();if(!editing)return;if(!editDate||num(editArea)<0){setMessage('Tanggal dan luas Actual wajib valid.');return}setBusy(true);try{const{db,username}=await writerContext(user),d=selectedDaily,actualAreaHa=num(editArea),payload:Record<string,unknown>={date:editDate,year:Number(editDate.slice(0,4)),monthKey:editDate.slice(0,7),actualAreaHa,manpower:num(editManpower),unitName:editUnit,foreman:editForeman,notes:editNotes,dailyPlanId:d?.dailyPlanId||'',dailyLinkStatus:d?'LINKED':'NOT_FOUND',monthlyPlanLineId:d?.monthlyPlanLineId||'',monthlyLinkStatus:d?.monthlyPlanLineId?'LINKED':'NOT_APPLICABLE',plannedDailyAreaHa:d?.areaHa||0,dailyVarianceHa:d?d.areaHa-actualAreaHa:0,lastModifiedSource:'WEB',updatedAt:serverTimestamp(),updatedBy:username};if(d){Object.assign(payload,{shift:d.shift,sourceType:d.sourceType||editing.sourceType,companyCode:d.companyCode,farm:d.farm,pid:d.pid,paddockRaw:d.pid,activity:d.activity,masterPending:false})}await setDoc(doc(db,'daily_reports',editing.id),payload,{merge:true});setMessage('Actual '+editing.actualReportId+' berhasil diperbarui. Monthly progress otomatis mengikuti monthlyPlanLineId dari Daily Plan yang dipilih.');cancelEdit();await load()}catch(err){setMessage(err instanceof Error?err.message:'Actual gagal diperbarui.')}finally{setBusy(false)}}

  return <section><div className="section-head"><div><div className="eyebrow">ACTUAL PLAN</div><h2>Daftar Actual / Daily Report</h2><p className="muted">Gunakan Edit untuk memperbaiki luas actual atau memilih Daily Plan yang benar. Saat Daily Plan diganti, monthlyPlanLineId ikut tersinkron otomatis.</p></div><button type="button" disabled={busy} onClick={()=>void load()}>{busy?'Memuat…':'Refresh'}</button></div>{message&&<div className="alert">{message}</div>}
  <div className="panel" style={{marginTop:18}}><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(170px,1fr))',gap:12}}><label><span>Bulan</span><select value={month} onChange={e=>setMonth(e.target.value)}><option value="ALL">Semua Bulan</option>{months.map(x=><option key={x}>{x}</option>)}</select></label><label><span>Sumber</span><select value={source} onChange={e=>setSource(e.target.value)}><option value="ALL">Semua Sumber</option><option value="MONTHLY">MONTHLY</option><option value="ADHOC">ADHOC</option><option value="SUPPORT">SUPPORT</option><option value="HISTORICAL">HISTORICAL</option></select></label><label><span>Daily Link</span><select value={link} onChange={e=>setLink(e.target.value)}><option value="ALL">Semua Status</option><option value="LINKED">LINKED</option><option value="NOT_FOUND">PENDING</option><option value="AMBIGUOUS">AMBIGUOUS</option></select></label><label><span>Company</span><select value={company} onChange={e=>{setCompany(e.target.value);setFarm('ALL')}}><option value="ALL">Semua Company</option>{companies.map(x=><option key={x}>{x}</option>)}</select></label><label><span>Farm</span><select value={farm} onChange={e=>setFarm(e.target.value)}><option value="ALL">Semua Farm</option>{farms.map(x=><option key={x}>{x}</option>)}</select></label><label><span>Kegiatan</span><select value={activity} onChange={e=>setActivity(e.target.value)}><option value="ALL">Semua Kegiatan</option>{activities.map(x=><option key={x}>{x}</option>)}</select></label><label><span>Cari</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Actual ID / Daily ID / Monthly ID / PID / mandor"/></label></div></div>
  <div className="cards" style={{marginTop:18}}><div className="card"><span>ACTUAL</span><strong>{filtered.length}</strong></div><div className="card"><span>LUAS ACTUAL</span><strong>{ha(totals.area)}</strong></div><div className="card"><span>TENAGA</span><strong>{totals.man}</strong></div><div className="card"><span>DAILY LINKED</span><strong>{totals.linked}</strong></div><div className="card"><span>DAILY PENDING</span><strong>{totals.pending}</strong></div></div>
  <div className="panel" style={{marginTop:18}}><div className="table-wrap"><table><thead><tr><th>Actual ID</th><th>Tanggal</th><th>Sumber</th><th>Plan ID Daily</th><th>Plan ID Legacy</th><th>Company / Farm</th><th>PID</th><th>Kegiatan</th><th>Actual</th><th>Plan Harian</th><th>Selisih</th><th>Daily Link</th><th>Monthly Link</th><th>Mandor</th><th>Aksi</th></tr></thead><tbody>{filtered.map(r=><tr key={r.id}><td><strong>{r.actualReportId}</strong></td><td>{date(r.date)}</td><td>{r.sourceType}</td><td>{r.dailySourcePlanIdRaw||'-'}</td><td>{r.monthlyLegacyPlanId||'-'}</td><td>{r.companyCode||'-'}<br/><span className="muted">{r.farm||'-'}</span></td><td>{r.pid}</td><td>{r.activity}</td><td>{ha(r.actualAreaHa)}</td><td>{r.plannedDailyAreaHa?ha(r.plannedDailyAreaHa):'-'}</td><td>{r.plannedDailyAreaHa?ha(r.dailyVarianceHa):'-'}</td><td>{r.dailyLinkStatus}<br/><span className="muted">{r.dailyPlanId||'-'}</span></td><td>{r.monthlyLinkStatus}<br/><span className="muted">{r.monthlyPlanLineId||'-'}</span></td><td>{r.foreman||'-'}</td><td><button type="button" onClick={()=>startEdit(r)}>Edit</button></td></tr>)}</tbody></table></div></div>
  {editing&&<form id="actual-edit-panel" className="panel" style={{marginTop:18}} onSubmit={saveEdit}><div className="section-head"><div><div className="eyebrow">EDIT ACTUAL</div><h3>{editing.actualReportId}</h3><p className="muted">Pilih Daily Plan yang benar untuk memperbaiki link Actual → Daily → Monthly. Actual ID tetap.</p></div><button type="button" onClick={cancelEdit}>Batal</button></div><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(190px,1fr))',gap:12}}>
    <label><span>Tanggal Actual</span><input type="date" value={editDate} onChange={e=>setEditDate(e.target.value)}/></label><label><span>Luas Aktual (Ha)</span><input type="number" min="0" step="0.0001" value={editArea} onChange={e=>setEditArea(e.target.value)}/></label><label><span>Paddock</span><input value={editContext?.paddock||''} readOnly title="Mengikuti Daily Plan yang dipilih"/></label><label><span>Shift</span><input value={editContext?.shift||''} readOnly title="Mengikuti Daily Plan yang dipilih"/></label><label><span>Kegiatan / Activity</span><input value={editContext?.activity||''} readOnly title="Mengikuti Daily Plan yang dipilih"/></label><label><span>Monthly Plan</span><input value={editContext?.monthlyPlanLineId||''} readOnly title="Mengikuti Daily Plan yang dipilih"/></label><label><span>Company</span><input value={editContext?.companyCode||''} readOnly/></label><label><span>Farm</span><input value={editContext?.farm||''} readOnly/></label><label><span>Luas Daily Plan</span><input value={editContext?.plannedAreaHa?ha(editContext.plannedAreaHa):'-'} readOnly/></label><label><span>Tenaga Kerja</span><input type="number" min="0" value={editManpower} onChange={e=>setEditManpower(e.target.value)}/></label><label><span>Unit</span><input value={editUnit} onChange={e=>setEditUnit(e.target.value)}/></label><label><span>Mandor</span><input value={editForeman} onChange={e=>setEditForeman(e.target.value)}/></label><label><span>Keterangan</span><input value={editNotes} onChange={e=>setEditNotes(e.target.value)}/></label><label><span>Cari Daily Plan</span><input value={dailyQuery} onChange={e=>setDailyQuery(e.target.value)} placeholder="Daily ID / Monthly ID / PID / Activity / tanggal"/></label><label><span>Link Daily Plan</span><select value={editDaily} onChange={e=>setEditDaily(e.target.value)}><option value="">Tanpa Daily Link / PENDING</option>{dailyChoices.map(x=><option key={x.id} value={x.dailyPlanId}>{x.dailyPlanId} — {x.date} — Shift {x.shift||'-'} — {x.pid} — {x.activity}</option>)}</select></label>
  </div>{editContext&&<div className="alert" style={{marginTop:12}}><strong>Konteks pekerjaan</strong><br/>Paddock: {editContext.paddock||'-'} · Shift: {editContext.shift||'-'} · Activity: {editContext.activity||'-'}<br/>Monthly: {editContext.monthlyPlanLineId||'tidak terkait'} · Company/Farm: {editContext.companyCode||'-'} / {editContext.farm||'-'} · Daily Plan: {editContext.plannedAreaHa?ha(editContext.plannedAreaHa):'-'}</div>}<button type="submit" className="primary" disabled={busy} style={{marginTop:14}}>Simpan Perubahan Actual</button></form>}
  <div className="panel" style={{marginTop:18}}><h3>Riwayat Import Actual</h3><div className="table-wrap"><table><thead><tr><th>Waktu</th><th>File</th><th>Actual</th><th>C/U/N/P</th><th>Daily L/P</th><th>Monthly Linked</th><th>Master Pending</th><th>W/E</th><th>Oleh</th></tr></thead><tbody>{logs.map(x=><tr key={x.id}><td>{dateTime(x.importedAt)}</td><td>{x.sourceFileName}</td><td>{x.total}</td><td>{x.created}/{x.updated}/{x.unchanged}/{x.protected}</td><td>{x.dailyLinked}/{x.dailyPending}</td><td>{x.monthlyLinked}</td><td>{x.masterPending}</td><td>{x.warnings}/{x.errors}</td><td>{x.importedBy}</td></tr>)}</tbody></table></div></div></section>
}
