import { FormEvent, useEffect, useMemo, useState } from 'react'
import { collection, doc, getDoc, getDocs, serverTimestamp, setDoc } from 'firebase/firestore'
import { firebaseAuth, firestoreDb } from './firebase'
import type { User } from './types'

type Props={user:User}
type Daily={id:string;dailyPlanId:string;date:string;shift:string;monthlyPlanLineId:string;sourceType:string;companyCode:string;farm:string;pid:string;activity:string;description:string;areaHa:number}
type ActualRef={actualReportId:string}

function text(v:unknown){return v===null||v===undefined?'':String(v).trim()}
function num(v:unknown){const n=Number(v||0);return Number.isFinite(n)?n:0}
async function writer(appUser:User){const db=firestoreDb,auth=firebaseAuth;if(!db||!auth)throw new Error('Firebase belum tersedia.');const current=auth.currentUser;if(!current)throw new Error('Login Firebase tidak tersedia.');const snap=await getDoc(doc(db,'users',current.uid));if(!snap.exists())throw new Error('Profil user tidak ditemukan.');const p=snap.data() as Record<string,unknown>;if(p.active!==true||!['owner','asisten'].includes(text(p.role))||!['owner','asisten'].includes(appUser.role))throw new Error('Role tidak memiliki izin membuat Actual Plan.');return{db,username:text(p.username)||appUser.username}}

export default function ActualPlanWebEntryPanel({user}:Props){
  const[daily,setDaily]=useState<Daily[]>([]),[actualIds,setActualIds]=useState<ActualRef[]>([]),[dailyId,setDailyId]=useState(''),[date,setDate]=useState(new Date().toISOString().slice(0,10)),[area,setArea]=useState(''),[manpower,setManpower]=useState('0'),[unitName,setUnitName]=useState(''),[foreman,setForeman]=useState(''),[notes,setNotes]=useState(''),[query,setQuery]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('')
  async function load(){if(!firestoreDb)return;setBusy(true);try{const[d,a]=await Promise.all([getDocs(collection(firestoreDb,'daily_plans')),getDocs(collection(firestoreDb,'daily_reports'))]);setDaily(d.docs.map(x=>{const r=x.data() as Record<string,unknown>;return{id:x.id,dailyPlanId:text(r.dailyPlanId||x.id),date:text(r.date),shift:text(r.shift),monthlyPlanLineId:text(r.monthlyPlanLineId),sourceType:text(r.sourceType),companyCode:text(r.companyCode),farm:text(r.farm),pid:text(r.pid),activity:text(r.activity),description:text(r.description),areaHa:num(r.areaHa)}}).sort((a,b)=>b.date.localeCompare(a.date)||a.dailyPlanId.localeCompare(b.dailyPlanId)));setActualIds(a.docs.map(x=>({actualReportId:text((x.data() as Record<string,unknown>).actualReportId||x.id)})))}catch(e){setMessage(e instanceof Error?e.message:'Daily Plan gagal dimuat.')}finally{setBusy(false)}}
  useEffect(()=>{void load()},[])
  const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return daily.filter(x=>!q||[x.dailyPlanId,x.monthlyPlanLineId,x.pid,x.activity,x.description,x.companyCode,x.farm,x.date].join(' ').toLowerCase().includes(q))},[daily,query])
  const selected=daily.find(x=>x.id===dailyId)||null
  function nextId(){const prefix='AR-'+date.replaceAll('-','')+'-';const n=actualIds.map(x=>x.actualReportId.startsWith(prefix)?Number(x.actualReportId.slice(prefix.length)):0).filter(Number.isFinite).reduce((m,x)=>Math.max(m,x),0)+1;return prefix+String(n).padStart(4,'0')}
  async function save(e:FormEvent){e.preventDefault();if(!selected||!date||num(area)<0){setMessage('Daily Plan, tanggal aktual, dan luas aktual wajib valid.');return}setBusy(true);try{const{db,username}=await writer(user),actualReportId=nextId(),actualAreaHa=num(area),monthlyPlanLineId=selected.monthlyPlanLineId;await setDoc(doc(db,'daily_reports',actualReportId),{actualReportId,dailySourcePlanIdRaw:selected.dailyPlanId,sourceType:selected.sourceType||'MONTHLY',dailyPlanId:selected.dailyPlanId,dailyLinkStatus:'LINKED',monthlyPlanLineId,monthlyLinkStatus:monthlyPlanLineId?'LINKED':'NOT_APPLICABLE',date,year:Number(date.slice(0,4)),monthKey:date.slice(0,7),shift:selected.shift,activity:selected.activity,paddockRaw:selected.pid,pid:selected.pid,actualAreaHa,areaUnit:'Ha',manpower:num(manpower),unitName,unitReady:0,unitStandby:0,unitBreakdown:0,foreman,notes,materials:[],plannedDailyAreaHa:selected.areaHa,dailyVarianceHa:selected.areaHa-actualAreaHa,companyCode:selected.companyCode,farm:selected.farm,masterPending:false,sourceOrigin:'WEB',lastModifiedSource:'WEB',createdAt:serverTimestamp(),createdBy:username,updatedAt:serverTimestamp(),updatedBy:username});setActualIds(x=>[...x,{actualReportId}]);setArea('');setNotes('');setMessage('Actual berhasil disimpan: '+actualReportId+'. Monthly balance akan menghitung ulang dari Actual linked ini.')}catch(err){setMessage(err instanceof Error?err.message:'Gagal menyimpan Actual.')}finally{setBusy(false)}}
  return <section><div className="section-head"><div><div className="eyebrow">ACTUAL PLAN</div><h2>Input Actual dari Daily Plan</h2><p className="muted">Pilih Daily Plan yang sudah dibuat. Actual menyimpan dailyPlanId dan monthlyPlanLineId secara eksplisit, sehingga luas aktual otomatis masuk ke progress Monthly Plan.</p></div><button type="button" onClick={()=>void load()} disabled={busy}>Refresh</button></div>{message&&<div className="alert">{message}</div>}
  <form className="panel" onSubmit={save}><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(190px,1fr))',gap:12}}>
  <label><span>Cari Daily Plan</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Daily ID / Monthly ID / PID / Activity"/></label>
  <label><span>Daily Plan ID</span><select value={dailyId} onChange={e=>{setDailyId(e.target.value);const x=daily.find(r=>r.id===e.target.value);if(x)setDate(x.date)}}><option value="">Pilih Daily Plan</option>{filtered.slice(0,400).map(x=><option key={x.id} value={x.id}>{x.dailyPlanId} — {x.date} — {x.pid} — {x.activity}</option>)}</select></label>
  <label><span>Tanggal Actual</span><input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label>
  <label><span>Luas Aktual (Ha)</span><input type="number" min="0" step="0.0001" value={area} onChange={e=>setArea(e.target.value)}/></label>
  <label><span>Tenaga Kerja</span><input type="number" min="0" step="1" value={manpower} onChange={e=>setManpower(e.target.value)}/></label>
  <label><span>Nama Unit</span><input value={unitName} onChange={e=>setUnitName(e.target.value)} placeholder="Opsional"/></label>
  <label><span>Mandor</span><input value={foreman} onChange={e=>setForeman(e.target.value)} placeholder="Opsional"/></label>
  <label><span>Keterangan</span><input value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Opsional"/></label></div>
  {selected&&<div className="alert" style={{marginTop:14}}><strong>{selected.dailyPlanId}</strong> · Monthly {selected.monthlyPlanLineId||'tidak terkait'} · {selected.pid} · {selected.activity}<br/>Luas Daily Plan: {selected.areaHa} Ha · Tanggal Plan: {selected.date} · Shift {selected.shift||'-'}</div>}
  <button type="submit" className="primary" disabled={busy||!selected} style={{marginTop:14}}>Simpan Actual</button></form></section>
}
