import { useEffect, useMemo, useState } from 'react'
import { collection, getDocs } from 'firebase/firestore'
import { firestoreDb } from './firebase'

type MaterialLine={material:string;dosePerHa:number;doseUnit:string;totalMaterial:number;unit:string}
type DailyRow={id:string;dailyPlanId:string;sourcePlanIdRaw:string;sourceType:string;monthlyLinkStatus:string;monthlyPlanLineId:string;date:string;monthKey:string;shift:string;activity:string;description:string;paddockRaw:string;pid:string;areaHa:number;areaUnit:string;manpower:number;unitName:string;unitReady:number;unitStandby:number;unitBreakdown:number;foreman:string;notes:string;companyCode:string;farm:string;stage:string;masterVariety:string;masterPending:boolean;materials:MaterialLine[];lastModifiedSource:string}
type ImportLog={id:string;sourceFileName:string;total:number;sourceRows:number;created:number;updated:number;unchanged:number;protected:number;monthly:number;adhoc:number;support:number;linked:number;masterPending:number;warnings:number;errors:number;importedBy:string;importedAt:string}

function text(value:unknown){return value===null||value===undefined?'':String(value).trim()}
function num(value:unknown){const n=Number(value||0);return Number.isFinite(n)?n:0}
function dateValue(value:unknown){if(!value)return'';if(typeof value==='string')return value;if(typeof value==='object'&&value!==null&&'toDate' in value&&typeof (value as {toDate?:unknown}).toDate==='function'){try{return((value as {toDate:()=>Date}).toDate()).toISOString()}catch{return''}}return''}
function materialsFromData(value:unknown):MaterialLine[]{if(!Array.isArray(value))return[];return value.map(item=>{const x=(item&&typeof item==='object'?item:{}) as Record<string,unknown>;return{material:text(x.material),dosePerHa:num(x.dosePerHa),doseUnit:text(x.doseUnit),totalMaterial:num(x.totalMaterial),unit:text(x.unit)}}).filter(x=>x.material||x.dosePerHa||x.totalMaterial)}
function rowFromData(id:string,data:Record<string,unknown>):DailyRow{return{id,dailyPlanId:text(data.dailyPlanId||id),sourcePlanIdRaw:text(data.sourcePlanIdRaw),sourceType:text(data.sourceType),monthlyLinkStatus:text(data.monthlyLinkStatus),monthlyPlanLineId:text(data.monthlyPlanLineId),date:text(data.date),monthKey:text(data.monthKey),shift:text(data.shift),activity:text(data.activity),description:text(data.description),paddockRaw:text(data.paddockRaw),pid:text(data.pid),areaHa:num(data.areaHa),areaUnit:text(data.areaUnit)||'Ha',manpower:num(data.manpower),unitName:text(data.unitName),unitReady:num(data.unitReady),unitStandby:num(data.unitStandby),unitBreakdown:num(data.unitBreakdown),foreman:text(data.foreman),notes:text(data.notes),companyCode:text(data.companyCode).toUpperCase(),farm:text(data.farm),stage:text(data.stage),masterVariety:text(data.masterVariety),masterPending:data.masterPending===true,materials:materialsFromData(data.materials),lastModifiedSource:text(data.lastModifiedSource)}}
function logFromData(id:string,data:Record<string,unknown>):ImportLog{return{id,sourceFileName:text(data.sourceFileName),total:num(data.total),sourceRows:num(data.sourceRows),created:num(data.created),updated:num(data.updated),unchanged:num(data.unchanged),protected:num(data.protected),monthly:num(data.monthly),adhoc:num(data.adhoc),support:num(data.support),linked:num(data.linked),masterPending:num(data.masterPending),warnings:num(data.warnings),errors:num(data.errors),importedBy:text(data.importedBy),importedAt:dateValue(data.importedAt)}}
function formatHa(value:number,digits=2){return new Intl.NumberFormat('id-ID',{minimumFractionDigits:digits,maximumFractionDigits:digits}).format(value)+' Ha'}
function formatDate(value:string){if(!value)return'-';const d=new Date(value+'T00:00:00');return Number.isNaN(d.getTime())?value:d.toLocaleDateString('id-ID',{day:'2-digit',month:'2-digit',year:'numeric'})}
function formatDateTime(value:string){if(!value)return'-';const d=new Date(value);return Number.isNaN(d.getTime())?value:d.toLocaleString('id-ID',{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'})}

export default function DailyPlanListPanel(){
  const[rows,setRows]=useState<DailyRow[]>([]),[logs,setLogs]=useState<ImportLog[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState('')
  const[month,setMonth]=useState('ALL'),[source,setSource]=useState('ALL'),[company,setCompany]=useState('ALL'),[farm,setFarm]=useState('ALL'),[shift,setShift]=useState('ALL'),[activity,setActivity]=useState('ALL'),[query,setQuery]=useState('')

  async function load(){if(!firestoreDb){setMessage('Firestore belum tersedia.');return}setBusy(true);setMessage('Memuat Daily Plan…');try{const[planSnap,logSnap]=await Promise.all([getDocs(collection(firestoreDb,'daily_plans')),getDocs(collection(firestoreDb,'daily_plan_import_logs'))]);const next=planSnap.docs.map(x=>rowFromData(x.id,x.data() as Record<string,unknown>)).sort((a,b)=>b.date.localeCompare(a.date)||a.shift.localeCompare(b.shift)||a.pid.localeCompare(b.pid,undefined,{numeric:true})||a.activity.localeCompare(b.activity));const nextLogs=logSnap.docs.map(x=>logFromData(x.id,x.data() as Record<string,unknown>)).sort((a,b)=>b.importedAt.localeCompare(a.importedAt)).slice(0,10);setRows(next);setLogs(nextLogs);setMessage('Daily Plan siap: '+next.length+' pekerjaan.')}catch(error){setMessage(error instanceof Error?error.message:'Daily Plan gagal dimuat.')}finally{setBusy(false)}}
  useEffect(()=>{void load()},[])

  const months=useMemo(()=>[...new Set(rows.map(x=>x.monthKey).filter(Boolean))].sort().reverse(),[rows])
  const companies=useMemo(()=>[...new Set(rows.map(x=>x.companyCode).filter(Boolean))].sort(),[rows])
  const farms=useMemo(()=>[...new Set(rows.filter(x=>company==='ALL'||x.companyCode===company).map(x=>x.farm).filter(Boolean))].sort((a,b)=>a.localeCompare(b,undefined,{numeric:true})),[rows,company])
  const shifts=useMemo(()=>[...new Set(rows.map(x=>x.shift).filter(Boolean))].sort((a,b)=>a.localeCompare(b,undefined,{numeric:true})),[rows])
  const activities=useMemo(()=>[...new Set(rows.map(x=>x.activity).filter(Boolean))].sort(),[rows])
  const filtered=useMemo(()=>{const needle=query.trim().toLowerCase();return rows.filter(row=>(month==='ALL'||row.monthKey===month)&&(source==='ALL'||row.sourceType===source)&&(company==='ALL'||row.companyCode===company)&&(farm==='ALL'||row.farm===farm)&&(shift==='ALL'||row.shift===shift)&&(activity==='ALL'||row.activity===activity)&&(!needle||[row.dailyPlanId,row.sourcePlanIdRaw,row.monthlyPlanLineId,row.pid,row.paddockRaw,row.activity,row.description,row.foreman,row.unitName,row.notes,...row.materials.map(x=>x.material)].join(' ').toLowerCase().includes(needle)))},[rows,month,source,company,farm,shift,activity,query])
  const totals=useMemo(()=>filtered.reduce((acc,row)=>({area:acc.area+row.areaHa,manpower:acc.manpower+row.manpower,monthly:acc.monthly+(row.sourceType==='MONTHLY'?1:0),adhoc:acc.adhoc+(row.sourceType==='ADHOC'?1:0),support:acc.support+(row.sourceType==='SUPPORT'?1:0),pending:acc.pending+(row.masterPending?1:0)}),{area:0,manpower:0,monthly:0,adhoc:0,support:0,pending:0}),[filtered])

  return <section>
    <div className="section-head"><div><div className="eyebrow">DAILY PLAN</div><h2>Daftar Daily Plan</h2><p className="muted">Satu baris daftar mewakili satu pekerjaan lapangan; beberapa baris bahan dari Excel sudah digabung ke dalam satu Daily Plan.</p></div><button type="button" disabled={busy} onClick={()=>void load()}>{busy?'Memuat…':'Refresh'}</button></div>
    {message&&<div className="alert">{message}</div>}
    <div className="panel" style={{marginTop:18}}><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(170px,1fr))',gap:12}}>
      <label><span>Bulan</span><select value={month} onChange={e=>setMonth(e.target.value)}><option value="ALL">Semua Bulan</option>{months.map(x=><option key={x}>{x}</option>)}</select></label>
      <label><span>Sumber</span><select value={source} onChange={e=>setSource(e.target.value)}><option value="ALL">Semua Sumber</option><option value="MONTHLY">MONTHLY</option><option value="ADHOC">ADHOC</option><option value="SUPPORT">SUPPORT</option></select></label>
      <label><span>Company</span><select value={company} onChange={e=>{setCompany(e.target.value);setFarm('ALL')}}><option value="ALL">Semua Company</option>{companies.map(x=><option key={x}>{x}</option>)}</select></label>
      <label><span>Farm</span><select value={farm} onChange={e=>setFarm(e.target.value)}><option value="ALL">Semua Farm</option>{farms.map(x=><option key={x}>{x}</option>)}</select></label>
      <label><span>Shift</span><select value={shift} onChange={e=>setShift(e.target.value)}><option value="ALL">Semua Shift</option>{shifts.map(x=><option key={x}>{x}</option>)}</select></label>
      <label><span>Kegiatan</span><select value={activity} onChange={e=>setActivity(e.target.value)}><option value="ALL">Semua Kegiatan</option>{activities.map(x=><option key={x}>{x}</option>)}</select></label>
      <label><span>Cari</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Daily ID / Plan ID / PID / bahan / mandor"/></label>
    </div></div>
    <div className="cards" style={{marginTop:18}}><div className="card"><span>PEKERJAAN</span><strong>{filtered.length}</strong></div><div className="card"><span>LUAS</span><strong>{formatHa(totals.area)}</strong></div><div className="card"><span>TENAGA</span><strong>{totals.manpower}</strong></div><div className="card"><span>MONTHLY</span><strong>{totals.monthly}</strong></div><div className="card"><span>ADHOC</span><strong>{totals.adhoc}</strong></div><div className="card"><span>SUPPORT</span><strong>{totals.support}</strong></div><div className="card"><span>MASTER PENDING</span><strong>{totals.pending}</strong></div></div>
    <div className="panel" style={{marginTop:18}}><div className="table-wrap"><table><thead><tr><th>Daily Plan ID</th><th>Tanggal / Shift</th><th>Sumber</th><th>Plan ID</th><th>Company / Farm</th><th>PID</th><th>Kegiatan</th><th>Luas</th><th>Tenaga</th><th>Unit</th><th>Mandor</th><th>Bahan</th><th>Link Monthly</th><th>Keterangan</th></tr></thead><tbody>{filtered.map(row=><tr key={row.id}><td><strong>{row.dailyPlanId}</strong></td><td>{formatDate(row.date)}<br/><span className="muted">Shift {row.shift||'-'}</span></td><td>{row.sourceType}</td><td>{row.sourcePlanIdRaw||'-'}</td><td>{row.companyCode||'-'}<br/><span className="muted">{row.farm||'-'}</span></td><td>{row.pid}<br/><span className="muted">{row.masterPending?'MASTER PENDING':row.stage||'-'}</span></td><td>{row.activity}<br/><span className="muted">{row.description||'-'}</span></td><td>{formatHa(row.areaHa)}</td><td>{row.manpower}</td><td>{row.unitName||'-'}<br/><span className="muted">R {row.unitReady} / S {row.unitStandby} / B {row.unitBreakdown}</span></td><td>{row.foreman||'-'}</td><td>{row.materials.length?row.materials.map((x,i)=><div key={i}>{x.material} — {x.dosePerHa} {x.doseUnit}</div>):'-'}</td><td>{row.monthlyLinkStatus}<br/><span className="muted">{row.monthlyPlanLineId||'-'}</span></td><td>{row.notes||'-'}</td></tr>)}</tbody></table></div>{!filtered.length&&<p className="muted">Tidak ada Daily Plan sesuai filter.</p>}</div>
    <div className="panel" style={{marginTop:18}}><h3>Riwayat Import Daily Plan</h3><p className="muted">10 import terakhir.</p><div className="table-wrap"><table><thead><tr><th>Waktu</th><th>File</th><th>Baris Excel</th><th>Daily Plan</th><th>C/U/N/P</th><th>M/A/S</th><th>Linked</th><th>Pending</th><th>W/E</th><th>Oleh</th></tr></thead><tbody>{logs.map(log=><tr key={log.id}><td>{formatDateTime(log.importedAt)}</td><td>{log.sourceFileName}</td><td>{log.sourceRows}</td><td>{log.total}</td><td>{log.created}/{log.updated}/{log.unchanged}/{log.protected}</td><td>{log.monthly}/{log.adhoc}/{log.support}</td><td>{log.linked}</td><td>{log.masterPending}</td><td>{log.warnings}/{log.errors}</td><td>{log.importedBy}</td></tr>)}</tbody></table></div>{!logs.length&&<p className="muted">Belum ada riwayat import.</p>}</div>
  </section>
}
