import { FormEvent, useEffect, useMemo, useState } from 'react'
import { collection, doc, getDoc, getDocs, serverTimestamp, setDoc } from 'firebase/firestore'
import { firebaseAuth, firestoreDb } from './firebase'
import type { User } from './types'

type Props={user:User}
type Monthly={id:string;planLineId:string;monthKey:string;week:string;companyCode:string;farm:string;pid:string;description:string;activity:string;targetAreaHa:number;type:string;activityCategory:string;stage:string;masterVariety:string;componentsSnapshot:unknown[]}
type Daily={dailyPlanId:string;monthlyPlanLineId:string;areaHa:number}

function text(v:unknown){return v===null||v===undefined?'':String(v).trim()}
function num(v:unknown){const n=Number(v||0);return Number.isFinite(n)?n:0}
async function writer(appUser:User){const db=firestoreDb,auth=firebaseAuth;if(!db||!auth)throw new Error('Firebase belum tersedia.');const current=auth.currentUser;if(!current)throw new Error('Login Firebase tidak tersedia.');const snap=await getDoc(doc(db,'users',current.uid));if(!snap.exists())throw new Error('Profil user tidak ditemukan.');const p=snap.data() as Record<string,unknown>;if(p.active!==true||!['owner','asisten'].includes(text(p.role))||!['owner','asisten'].includes(appUser.role))throw new Error('Role tidak memiliki izin membuat Daily Plan.');return{db,username:text(p.username)||appUser.username}}

export default function DailyPlanWebEntryPanel({user}:Props){
  const[monthly,setMonthly]=useState<Monthly[]>([]),[daily,setDaily]=useState<Daily[]>([]),[date,setDate]=useState(new Date().toISOString().slice(0,10)),[shift,setShift]=useState('1'),[monthlyId,setMonthlyId]=useState(''),[area,setArea]=useState(''),[manpower,setManpower]=useState('0'),[unitName,setUnitName]=useState(''),[foreman,setForeman]=useState(''),[notes,setNotes]=useState(''),[query,setQuery]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('')
  async function load(){if(!firestoreDb)return;setBusy(true);try{const[m,d]=await Promise.all([getDocs(collection(firestoreDb,'monthly_plans')),getDocs(collection(firestoreDb,'daily_plans'))]);setMonthly(m.docs.map(x=>{const r=x.data() as Record<string,unknown>;return{id:x.id,planLineId:text(r.planLineId||x.id),monthKey:text(r.monthKey),week:text(r.week),companyCode:text(r.companyCode),farm:text(r.farm),pid:text(r.pid),description:text(r.description),activity:text(r.activity),targetAreaHa:num(r.targetAreaHa),type:text(r.type),activityCategory:text(r.activityCategory),stage:text(r.stage),masterVariety:text(r.masterVariety),componentsSnapshot:Array.isArray(r.componentsSnapshot)?r.componentsSnapshot:[]}}).sort((a,b)=>b.monthKey.localeCompare(a.monthKey)||a.planLineId.localeCompare(b.planLineId,undefined,{numeric:true})));setDaily(d.docs.map(x=>{const r=x.data() as Record<string,unknown>;return{dailyPlanId:text(r.dailyPlanId||x.id),monthlyPlanLineId:text(r.monthlyPlanLineId),areaHa:num(r.areaHa)}}))}catch(e){setMessage(e instanceof Error?e.message:'Data Plan gagal dimuat.')}finally{setBusy(false)}}
  useEffect(()=>{void load()},[])
  const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return monthly.filter(x=>!q||[x.planLineId,x.pid,x.description,x.activity,x.companyCode,x.farm].join(' ').toLowerCase().includes(q))},[monthly,query])
  const selected=monthly.find(x=>x.id===monthlyId)||null
  const scheduled=selected?daily.filter(x=>x.monthlyPlanLineId===selected.planLineId).reduce((s,x)=>s+x.areaHa,0):0
  const remaining=selected?selected.targetAreaHa-scheduled:0
  function nextId(){const prefix='DP-'+date.replaceAll('-','')+'-';const n=daily.map(x=>x.dailyPlanId.startsWith(prefix)?Number(x.dailyPlanId.slice(prefix.length)):0).filter(Number.isFinite).reduce((m,x)=>Math.max(m,x),0)+1;return prefix+String(n).padStart(4,'0')}
  async function save(e:FormEvent){e.preventDefault();if(!selected||!date||num(area)<=0){setMessage('Monthly Plan, tanggal, dan luas Daily Plan wajib diisi.');return}if(num(area)>remaining+0.0001&&!window.confirm('Luas Daily Plan melebihi sisa belum dijadwalkan Monthly Plan. Tetap simpan?'))return;setBusy(true);try{const{db,username}=await writer(user),dailyPlanId=nextId();await setDoc(doc(db,'daily_plans',dailyPlanId),{dailyPlanId,sourcePlanIdRaw:selected.planLineId,sourceType:'MONTHLY',monthlyLinkStatus:'LINKED',monthlyPlanLineId:selected.planLineId,date,year:Number(date.slice(0,4)),monthKey:date.slice(0,7),shift,activity:selected.activity,description:selected.description,paddockRaw:selected.pid,pid:selected.pid,areaHa:num(area),areaUnit:'Ha',manpower:num(manpower),unitName,unitReady:0,unitStandby:0,unitBreakdown:0,foreman,notes,companyCode:selected.companyCode,farm:selected.farm,stage:selected.stage,masterVariety:selected.masterVariety,masterPending:false,materials:[],componentsSnapshot:selected.componentsSnapshot,type:selected.type,activityCategory:selected.activityCategory,sourceOrigin:'WEB',lastModifiedSource:'WEB',createdAt:serverTimestamp(),createdBy:username,updatedAt:serverTimestamp(),updatedBy:username});setDaily(x=>[...x,{dailyPlanId,monthlyPlanLineId:selected.planLineId,areaHa:num(area)}]);setArea('');setNotes('');setMessage('Daily Plan berhasil dibuat: '+dailyPlanId+' dari '+selected.planLineId)}catch(err){setMessage(err instanceof Error?err.message:'Gagal membuat Daily Plan.')}finally{setBusy(false)}}
  return <section><div className="section-head"><div><div className="eyebrow">DAILY PLAN</div><h2>Tambah dari Monthly Plan</h2><p className="muted">Daily Plan selalu menyimpan monthlyPlanLineId yang dipilih. Satu Monthly Plan dapat dipecah menjadi banyak Daily Plan pada tanggal berbeda.</p></div><button type="button" onClick={()=>void load()} disabled={busy}>Refresh</button></div>{message&&<div className="alert">{message}</div>}
  <form className="panel" onSubmit={save}><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(190px,1fr))',gap:12}}>
  <label><span>Cari Monthly Plan</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Plan ID / PID / Activity"/></label>
  <label><span>Monthly Plan ID</span><select value={monthlyId} onChange={e=>setMonthlyId(e.target.value)}><option value="">Pilih Monthly Plan</option>{filtered.slice(0,300).map(x=><option key={x.id} value={x.id}>{x.planLineId} — {x.pid} — {x.description}</option>)}</select></label>
  <label><span>Tanggal Daily Plan</span><input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label>
  <label><span>Shift</span><input value={shift} onChange={e=>setShift(e.target.value)} placeholder="1 / 2 / 3"/></label>
  <label><span>Luas Plan Harian (Ha)</span><input type="number" min="0" step="0.0001" value={area} onChange={e=>setArea(e.target.value)}/></label>
  <label><span>Tenaga Kerja</span><input type="number" min="0" step="1" value={manpower} onChange={e=>setManpower(e.target.value)}/></label>
  <label><span>Nama Unit</span><input value={unitName} onChange={e=>setUnitName(e.target.value)} placeholder="Opsional"/></label>
  <label><span>Mandor</span><input value={foreman} onChange={e=>setForeman(e.target.value)} placeholder="Opsional"/></label>
  <label><span>Keterangan</span><input value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Opsional"/></label></div>
  {selected&&<div className="alert" style={{marginTop:14}}><strong>{selected.planLineId}</strong> · {selected.pid} · {selected.description}<br/>Target Monthly: {selected.targetAreaHa} Ha · Sudah dijadwalkan: {scheduled.toFixed(2)} Ha · Sisa belum dijadwalkan: {remaining.toFixed(2)} Ha</div>}
  <button type="submit" className="primary" disabled={busy||!selected} style={{marginTop:14}}>Simpan Daily Plan</button></form></section>
}
