import { FormEvent, useEffect, useMemo, useState } from 'react'
import { collection, doc, getDoc, getDocs, serverTimestamp, setDoc } from 'firebase/firestore'
import { firebaseAuth, firestoreDb } from './firebase'
import { FALLBACK_COMPANIES, type CompanyRecord } from './companyMaster'
import type { User } from './types'

type Props={user:User}
type Paddock={pid:string;companyCode:string;farm:string;variety:string;stage:string;areaPaddockHa:number}
type Component={sequence:number;label:string;activeIngredient:string;dosePerHa:number;unit:string}
type Activity={id:string;activityCode:string;description:string;activity:string;type:string;activityCategory:string;companyScope:string;active:boolean;components:Component[]}

function text(v:unknown){return v===null||v===undefined?'':String(v).trim()}
function num(v:unknown){const n=Number(v||0);return Number.isFinite(n)?n:0}
function pad(v:number){return String(v).padStart(2,'0')}
function companyFromData(id:string,d:Record<string,unknown>):CompanyRecord{return{id,code:text(d.code||id).toUpperCase(),name:text(d.name),prefixes:Array.isArray(d.prefixes)?d.prefixes.map(x=>text(x).toUpperCase()).filter(Boolean):[],active:d.active!==false}}
function components(v:unknown):Component[]{if(!Array.isArray(v))return[];return v.map((x,i)=>{const d=(x&&typeof x==='object'?x:{}) as Record<string,unknown>;return{sequence:num(d.sequence)||i+1,label:text(d.label)||'Bahan '+(i+1),activeIngredient:text(d.activeIngredient),dosePerHa:num(d.dosePerHa),unit:text(d.unit)}}).filter(x=>x.activeIngredient&&x.dosePerHa>0)}
function planDocId(v:string){return encodeURIComponent(v.replaceAll('/','-')).slice(0,1400)}
function weekDates(monthKey:string,week:string){if(!/^\d{4}-\d{2}$/.test(monthKey))return{start:'',end:''};const[y,m]=monthKey.split('-').map(Number),last=new Date(y,m,0).getDate(),map:Record<string,[number,number]>={W1:[1,7],W2:[8,15],W3:[16,22],W4:[23,last]},range=map[week]||[1,last];return{start:monthKey+'-'+pad(range[0]),end:monthKey+'-'+pad(range[1])}}
async function writer(appUser:User){const db=firestoreDb,auth=firebaseAuth;if(!db||!auth)throw new Error('Firebase belum tersedia.');const current=auth.currentUser;if(!current)throw new Error('Login Firebase tidak tersedia.');const snap=await getDoc(doc(db,'users',current.uid));if(!snap.exists())throw new Error('Profil user tidak ditemukan.');const p=snap.data() as Record<string,unknown>;if(p.active!==true||!['owner','asisten'].includes(text(p.role))||!['owner','asisten'].includes(appUser.role))throw new Error('Role tidak memiliki izin membuat Monthly Plan.');return{db,username:text(p.username)||appUser.username}}

export default function MonthlyPlanWebEntryPanel({user}:Props){
  const[companies,setCompanies]=useState<CompanyRecord[]>([]),[paddocks,setPaddocks]=useState<Paddock[]>([]),[activities,setActivities]=useState<Activity[]>([]),[existingIds,setExistingIds]=useState<string[]>([])
  const[month,setMonth]=useState(new Date().toISOString().slice(0,7)),[week,setWeek]=useState('W1'),[company,setCompany]=useState('GPA'),[farm,setFarm]=useState(''),[pid,setPid]=useState(''),[activityId,setActivityId]=useState(''),[target,setTarget]=useState(''),[notes,setNotes]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('')
  async function load(){if(!firestoreDb)return;setBusy(true);try{const[c,p,a,m]=await Promise.all([getDocs(collection(firestoreDb,'master_companies')),getDocs(collection(firestoreDb,'master_paddocks')),getDocs(collection(firestoreDb,'master_activities')),getDocs(collection(firestoreDb,'monthly_plans'))]);setCompanies(c.empty?FALLBACK_COMPANIES:c.docs.map(x=>companyFromData(x.id,x.data() as Record<string,unknown>)).filter(x=>x.active));setPaddocks(p.docs.map(x=>{const d=x.data() as Record<string,unknown>;return{pid:text(d.pid||x.id).toUpperCase(),companyCode:text(d.companyCode).toUpperCase(),farm:text(d.farm),variety:text(d.variety),stage:text(d.currentStage||d.stage),areaPaddockHa:num(d.areaPlantedHa||d.areaPaddockHa)}}));setActivities(a.docs.map(x=>{const d=x.data() as Record<string,unknown>;return{id:x.id,activityCode:text(d.activityCode),description:text(d.description),activity:text(d.activity),type:text(d.type),activityCategory:text(d.activityCategory),companyScope:text(d.companyScope||'GLOBAL').toUpperCase(),active:d.active===true,components:components(d.components)}}));setExistingIds(m.docs.map(x=>text((x.data() as Record<string,unknown>).planLineId||x.id)))}catch(e){setMessage(e instanceof Error?e.message:'Master data gagal dimuat.')}finally{setBusy(false)}}
  useEffect(()=>{void load()},[])
  const farms=useMemo(()=>[...new Set(paddocks.filter(x=>!company||x.companyCode===company).map(x=>x.farm).filter(Boolean))].sort(),[paddocks,company])
  const pidOptions=useMemo(()=>paddocks.filter(x=>(!company||x.companyCode===company)&&(!farm||x.farm===farm)).map(x=>x.pid).sort((a,b)=>a.localeCompare(b,undefined,{numeric:true})),[paddocks,company,farm])
  const selectedPaddock=paddocks.find(x=>x.pid===pid.toUpperCase())||null
  const activityOptions=activities.filter(x=>x.active&&(x.companyScope==='GLOBAL'||x.companyScope===company)).sort((a,b)=>a.description.localeCompare(b.description))
  const selectedActivity=activityOptions.find(x=>x.id===activityId)||null
  const targetNum=num(target)
  function nextPlanId(){const prefix='MP-'+company+'-'+month.replace('-','')+'-';const seq=existingIds.map(x=>x.startsWith(prefix)?Number(x.slice(prefix.length)):0).filter(Number.isFinite).reduce((m,x)=>Math.max(m,x),0)+1;return prefix+String(seq).padStart(4,'0')}
  async function save(e:FormEvent){e.preventDefault();if(!month||!week||!company||!pid||!selectedActivity||targetNum<=0){setMessage('Bulan, Week, Company, PID, Activity, dan Target wajib diisi.');return}if(selectedPaddock&&targetNum>selectedPaddock.areaPaddockHa+0.0001){setMessage('Target melebihi Area Paddock master ('+selectedPaddock.areaPaddockHa+' Ha).');return}setBusy(true);try{const{db,username}=await writer(user),planLineId=nextPlanId(),dates=weekDates(month,week),[year,monthNumber]=month.split('-').map(Number);await setDoc(doc(db,'monthly_plans',planDocId(planLineId)),{planLineId,year,monthNumber,monthKey:month,monthLabel:new Date(year,monthNumber-1,1).toLocaleString('id-ID',{month:'short'}),inputDate:new Date().toISOString().slice(0,10),startDate:dates.start,endDate:dates.end,week,description:selectedActivity.description,pid:pid.toUpperCase(),targetAreaHa:targetNum,variety:selectedPaddock?.variety||'',sourceStatus:'Belum dikerjakan',status:'PLANNED',actualAreaHa:0,balanceHa:targetNum,calculatedBalanceHa:targetNum,activity:selectedActivity.activity,notes,companyCode:company,farm:selectedPaddock?.farm||farm,stage:selectedPaddock?.stage||'',areaPaddockHa:selectedPaddock?.areaPaddockHa||0,masterVariety:selectedPaddock?.variety||'',masterActivityId:selectedActivity.id,activityCode:selectedActivity.activityCode,type:selectedActivity.type,activityCategory:selectedActivity.activityCategory,componentsSnapshot:selectedActivity.components,sourceOrigin:'WEB',lastModifiedSource:'WEB',createdAt:serverTimestamp(),createdBy:username,updatedAt:serverTimestamp(),updatedBy:username});setExistingIds(x=>[...x,planLineId]);setTarget('');setNotes('');setMessage('Monthly Plan berhasil dibuat: '+planLineId)}catch(err){setMessage(err instanceof Error?err.message:'Gagal membuat Monthly Plan.')}finally{setBusy(false)}}
  return <section><div className="section-head"><div><div className="eyebrow">MONTHLY PLAN</div><h2>Tambah Plan via Web</h2><p className="muted">Target bulanan dibuat sebagai Plan Line. Actual tidak mengubah target; balance dihitung dari akumulasi Daily Report.</p></div><button type="button" onClick={()=>void load()} disabled={busy}>Refresh Master</button></div>{message&&<div className="alert">{message}</div>}
  <form className="panel" onSubmit={save}><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(190px,1fr))',gap:12}}>
  <label><span>Bulan</span><input type="month" value={month} onChange={e=>setMonth(e.target.value)}/></label>
  <label><span>Week</span><select value={week} onChange={e=>setWeek(e.target.value)}>{['W1','W2','W3','W4'].map(x=><option key={x}>{x}</option>)}</select></label>
  <label><span>Company</span><select value={company} onChange={e=>{setCompany(e.target.value);setFarm('');setPid('');setActivityId('')}}>{companies.map(x=><option key={x.id} value={x.code}>{x.code} — {x.name}</option>)}</select></label>
  <label><span>Farm</span><select value={farm} onChange={e=>{setFarm(e.target.value);setPid('')}}><option value="">Semua / belum diketahui</option>{farms.map(x=><option key={x}>{x}</option>)}</select></label>
  <label><span>PID</span><input list="monthly-web-pids" value={pid} onChange={e=>setPid(e.target.value.toUpperCase())} placeholder="JAGF-..."/><datalist id="monthly-web-pids">{pidOptions.map(x=><option key={x} value={x}/>)}</datalist></label>
  <label><span>Activity</span><select value={activityId} onChange={e=>setActivityId(e.target.value)}><option value="">Pilih Activity</option>{activityOptions.map(x=><option key={x.id} value={x.id}>{x.description} — {x.activity}</option>)}</select></label>
  <label><span>Target Luas (Ha)</span><input type="number" min="0" step="0.0001" value={target} onChange={e=>setTarget(e.target.value)}/></label>
  <label><span>Keterangan</span><input value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Opsional"/></label></div>
  {selectedPaddock&&<div className="alert" style={{marginTop:14}}>Master Paddock: {selectedPaddock.pid} · {selectedPaddock.farm||'-'} · {selectedPaddock.variety||'-'} · Area {selectedPaddock.areaPaddockHa} Ha</div>}
  {selectedActivity&&<div className="alert" style={{marginTop:10}}>Activity: {selectedActivity.description} · {selectedActivity.components.length} bahan aktif tersimpan sebagai snapshot.</div>}
  <button type="submit" className="primary" disabled={busy} style={{marginTop:14}}>Simpan Monthly Plan</button></form></section>
}
