import { useEffect, useMemo, useState } from 'react'
import { flushQueue, saveDraftFirestoreFirst, sendOrQueue } from './offline'
import { clearDraft, loadDraft, saveDraft } from './draftStore'
import PhotoPicker from './PhotoPicker'
import type { HoldInterval, MasterData, MaterialMaster, PlanMaster, QcRecord, User } from './types'

type Props={token:string;user:User;master:MasterData;initialRecords?:QcRecord[];onSaved:(records:QcRecord[])=>void;onCancelEdit?:()=>void}
type HoldDraft=HoldInterval&{id:string;file?:File;removePhoto?:boolean}
type SprayCard={
  id:string;recordId?:string;createdAt?:string;saveType?:string;photoDriveUrl?:string;removePhoto?:boolean;photo?:File
  startTime:string;endTime:string;unit:string;noUnit:string;area:string;activity:string;deskripsi:string;paddock:string;variety:string;type:string
  dropper:string;nozzle:string;dropletSize:string;height:string;rowSpacing:string;speed:string
  adjuvant:string;adjuvantDosage:string;actUsageAdjuvant:string;waterRate:string;waterQuality:string;actualUsage:string
  windSpeed:string;temperature:string;humidity:string;deltaT:string;weatherCondition:string;noted:string
  actualMaterials:Record<number,string>;holds:HoldDraft[]
}
type SprayDraft={sessionId:string;date:string;shift:string;mandor:string;assistant:string;cards:SprayCard[];activeCardId:string}
type LegacySprayDraft={form?:Record<string,string>;holds?:Array<HoldInterval&{file?:File;removePhoto?:boolean}>;actualMaterials?:Record<number,string>;mainPhoto?:File}

const today=()=>new Date().toISOString().slice(0,10)
const nowTime=()=>new Date().toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit',hour12:false})
const uid=()=>crypto.randomUUID()
const n=(value:unknown)=>Number(String(value??'').replace(',','.'))||0
const text=(value:unknown)=>value===undefined||value===null?'':String(value)
const unique=(values:unknown[])=>[...new Set(values.map(String).map(x=>x.trim()).filter(Boolean))]

function emptyCard():SprayCard{return{id:uid(),startTime:'',endTime:'',unit:'',noUnit:'',area:'',activity:'',deskripsi:'',paddock:'',variety:'',type:'',dropper:'No',nozzle:'',dropletSize:'',height:'',rowSpacing:'',speed:'',adjuvant:'',adjuvantDosage:'',actUsageAdjuvant:'',waterRate:'',waterQuality:'',actualUsage:'',windSpeed:'',temperature:'',humidity:'',deltaT:'',weatherCondition:'',noted:'',actualMaterials:{},holds:[]}}
function hasCardInput(card:SprayCard){return Boolean(card.recordId||card.unit||card.noUnit||card.area||card.activity||card.deskripsi||card.paddock||card.variety||card.type||card.startTime||card.endTime||card.noted||card.photo||card.photoDriveUrl||card.holds.length||Object.values(card.actualMaterials).some(Boolean))}
function cardFromRecord(record:QcRecord):SprayCard{return{id:uid(),recordId:record.id,createdAt:text(record.createdAt),saveType:text(record.saveType),photoDriveUrl:text(record.photoDriveUrl),startTime:text(record.startTime),endTime:text(record.endTime),unit:text(record.unit),noUnit:text(record.noUnit),area:text(record.area),activity:text(record.activity),deskripsi:text(record.deskripsi),paddock:record.paddock||'',variety:text(record.variety),type:text(record.type),dropper:text(record.dropper)||'No',nozzle:text(record.nozzle),dropletSize:text(record.dropletSize),height:text(record.height),rowSpacing:text(record.rowSpacing),speed:text(record.speed),adjuvant:text(record.adjuvant),adjuvantDosage:text(record.adjuvantDosage),actUsageAdjuvant:text(record.actUsageAdjuvant),waterRate:text(record.waterRate),waterQuality:text(record.waterQuality),actualUsage:text(record.actualUsage),windSpeed:text(record.windSpeed),temperature:text(record.temperature),humidity:text(record.humidity),deltaT:text(record.deltaT),weatherCondition:text(record.weatherCondition),noted:text(record.noted),actualMaterials:Object.fromEntries([0,1,2,3].map(i=>[i,text(record[`actUsagePesticide${i+1}`])]).filter(([,v])=>v)),holds:(record.holdIntervals||[]).map(h=>({...h,id:uid()}))}}
function legacyCard(saved:LegacySprayDraft):SprayCard{const form=saved.form||{},card=emptyCard();for(const key of Object.keys(card)){if(key in form&&(typeof card[key as keyof SprayCard]==='string'))(card as unknown as Record<string,unknown>)[key]=text(form[key])}card.actualMaterials=saved.actualMaterials||{};card.holds=(saved.holds||[]).map(h=>({...h,id:uid()}));card.photo=saved.mainPhoto;return card}
function normalizePlans(master:MasterData):PlanMaster[]{const raw=(master.plans||master.plan||[])as PlanMaster[];return raw.filter(p=>{const category=String(p.category||p.keterangan||'').trim().toLowerCase();if(category)return category==='spray';return Boolean(p.type||p.activity||p.description||p.deskripsi)})}
function Choice({values,value,onChange}:{values:string[];value:string;onChange:(value:string)=>void}){return <div className="choice-group">{values.length?values.map(item=><button key={item} type="button" className={value===item?'selected':''} onClick={()=>onChange(item)}>{item}</button>):<span className="muted">Tidak ada pilihan</span>}</div>}
function minutes(value:string){const m=/^(\d{2}):(\d{2})$/.exec(value);return m?Number(m[1])*60+Number(m[2]):NaN}
function durationLabel(value:number){return`${Math.floor(value/60)}j ${String(value%60).padStart(2,'0')}m`}
function timingFor(card:SprayCard){const start=minutes(card.startTime),end=minutes(card.endTime);if(!Number.isFinite(start)||!Number.isFinite(end)||end<=start)return{ready:false,total:0,working:0,effective:0,error:'Isi jam mulai dan selesai dengan benar.'};const ranges:Array<[number,number]>=[];for(const[i,h]of card.holds.entries()){if(!h.start&&!h.end)continue;const a=minutes(h.start),b=minutes(h.end);if(!Number.isFinite(a)||!Number.isFinite(b)||b<=a)return{ready:false,total:0,working:end-start,effective:0,error:`HOLD ${i+1}: jam tidak valid.`};if(a<start||b>end)return{ready:false,total:0,working:end-start,effective:0,error:`HOLD ${i+1}: harus berada dalam jam kerja.`};ranges.push([a,b])}ranges.sort((a,b)=>a[0]-b[0]);for(let i=1;i<ranges.length;i++)if(ranges[i][0]<ranges[i-1][1])return{ready:false,total:0,working:end-start,effective:0,error:'Waktu HOLD tidak boleh bertumpuk.'};const total=ranges.reduce((s,[a,b])=>s+b-a,0),working=end-start;return{ready:true,total,working,effective:working-total,error:''}}
async function loadImageElement(file:Blob):Promise<HTMLImageElement>{const url=URL.createObjectURL(file);try{return await new Promise<HTMLImageElement>((resolve,reject)=>{const x=new Image();x.onload=()=>resolve(x);x.onerror=()=>reject(new Error('decode'));x.src=url})}finally{window.setTimeout(()=>URL.revokeObjectURL(url),0)}}
async function photoData(file?:File):Promise<string>{if(!file)return'';if(file.size>6_000_000)throw new Error('Foto asli maksimal 6 MB.');if(!file.type.startsWith('image/'))throw new Error('File foto tidak valid. Pilih ulang dari Kamera atau Galeri.');let image:CanvasImageSource|undefined,width=0,height=0,bitmap:ImageBitmap|undefined;try{if('createImageBitmap'in window){try{bitmap=await createImageBitmap(file);image=bitmap;width=bitmap.width;height=bitmap.height}catch{}}if(!image){const img=await loadImageElement(file);image=img;width=img.naturalWidth;height=img.naturalHeight}if(!width||!height)throw new Error('decode');const scale=Math.min(1,1400/width),canvas=document.createElement('canvas');canvas.width=Math.round(width*scale);canvas.height=Math.round(height*scale);const context=canvas.getContext('2d');if(!context)throw new Error('canvas');context.drawImage(image,0,0,canvas.width,canvas.height);let quality=.72,result=canvas.toDataURL('image/jpeg',quality);while(result.length>2_400_000&&quality>.42){quality-=.08;result=canvas.toDataURL('image/jpeg',quality)}if(result.length>2_700_000)throw new Error('Foto masih terlalu besar setelah kompresi. Pilih foto lain.');return result}catch(error){if(error instanceof Error&&/terlalu besar/.test(error.message))throw error;throw new Error('Foto tidak dapat dibaca. Hapus foto tersebut lalu ambil/pilih ulang dari Kamera atau Galeri.')}finally{bitmap?.close?.()}}

export default function SprayForm({token,user,master,initialRecords=[],onSaved,onCancelEdit}:Props){
  const firstInitial=initialRecords[0],editing=initialRecords.length>0,editingUploaded=initialRecords.some(r=>r.saveType==='uploaded'),draftKey=`spray:${user.firebaseUid||user.username}`
  const[sessionId,setSessionId]=useState(()=>text(firstInitial?.sessionId)||`spraysession_${Date.now()}_${Math.random().toString(36).slice(2,7)}`)
  const[date,setDate]=useState(firstInitial?.date||today()),[shift,setShift]=useState(text(firstInitial?.shift)||'1'),[mandor,setMandor]=useState(text(firstInitial?.name)),[assistant,setAssistant]=useState(text(firstInitial?.nameOfAssistan))
  const[cards,setCards]=useState<SprayCard[]>(()=>initialRecords.length?initialRecords.map(cardFromRecord):[emptyCard()]),[activeCardId,setActiveCardId]=useState(()=>cards[0]?.id||''),[draftReady,setDraftReady]=useState(editing),[busy,setBusy]=useState(false),[message,setMessage]=useState('')

  useEffect(()=>{if(editing){setDraftReady(true);return}let alive=true;const legacyKey=`spray:${user.username}`;void(async()=>{let saved=await loadDraft<SprayDraft|LegacySprayDraft>(draftKey);if(!saved&&legacyKey!==draftKey)saved=await loadDraft<SprayDraft|LegacySprayDraft>(legacyKey);if(!alive||!saved)return;if('cards'in saved&&Array.isArray(saved.cards)){setSessionId(saved.sessionId||sessionId);setDate(saved.date||today());setShift(saved.shift||'1');setMandor(saved.mandor||'');setAssistant(saved.assistant||'');if(saved.cards.length){setCards(saved.cards);setActiveCardId(saved.activeCardId||saved.cards[0].id)}}else{const legacy=saved as LegacySprayDraft,form=legacy.form||{},card=legacyCard(legacy);setDate(form.date||today());setShift(form.shift||'1');setMandor(form.name||'');setAssistant(form.nameOfAssistan||'');setCards([card]);setActiveCardId(card.id)}})().finally(()=>{if(alive)setDraftReady(true)});return()=>{alive=false}},[draftKey,editing,user.username])
  useEffect(()=>{if(!editing&&draftReady)void saveDraft<SprayDraft>(draftKey,{sessionId,date,shift,mandor,assistant,cards,activeCardId}).catch(error=>setMessage(error instanceof Error?`Draft lokal gagal disimpan: ${error.message}`:'Draft lokal gagal disimpan.'))},[draftKey,editing,draftReady,sessionId,date,shift,mandor,assistant,cards,activeCardId])
  useEffect(()=>{const sync=async()=>{try{const result=await flushQueue(token);if(result.sent)setMessage(`${result.sent} data antrean berhasil disinkronkan.`)}catch(error){setMessage(error instanceof Error?error.message:'Sinkronisasi antrean gagal')}};window.addEventListener('online',sync);if(navigator.onLine)void sync();return()=>window.removeEventListener('online',sync)},[token])

  const plans=useMemo(()=>normalizePlans(master),[master]),unitTypes=useMemo(()=>Object.keys(master.unitMap||{}),[master.unitMap]),adjuvants=useMemo(()=>unique(((master.materials||[])as MaterialMaster[]).filter(x=>/adjuvant/i.test(`${x.slot||''} ${x.unit||''} ${x.description||''}`)).map(x=>x.material)),[master.materials])
  const activeCard=cards.find(c=>c.id===activeCardId)||cards[0],activeIndex=Math.max(0,cards.findIndex(c=>c.id===activeCard?.id))
  const total=useMemo(()=>({units:cards.filter(c=>c.noUnit||c.unit).length,area:cards.reduce((s,c)=>s+n(c.area),0),water:cards.reduce((s,c)=>s+n(c.actualUsage),0)}),[cards])
  function patchCard(id:string,patch:Partial<SprayCard>){setCards(old=>old.map(c=>c.id===id?{...c,...patch}:c))}
  function patchHold(cardId:string,holdId:string,patch:Partial<HoldDraft>){setCards(old=>old.map(c=>c.id===cardId?{...c,holds:c.holds.map(h=>h.id===holdId?{...h,...patch}:h)}:c))}
  function addHold(cardId:string){setCards(old=>old.map(c=>c.id===cardId?{...c,holds:[...c.holds,{id:uid(),start:nowTime(),end:'',reason:'',windSpeed:'',note:''}]}:c))}
  function addUnit(){const card=emptyCard();setCards(old=>[...old,card]);setActiveCardId(card.id)}
  function duplicateCard(card:SprayCard){const copy:SprayCard={...card,id:uid(),recordId:undefined,createdAt:undefined,saveType:undefined,noUnit:'',area:'',actualUsage:'',actUsageAdjuvant:'',actualMaterials:{},holds:[],noted:'',photo:undefined,photoDriveUrl:undefined,removePhoto:false};setCards(old=>[...old,copy]);setActiveCardId(copy.id)}
  function removeCard(card:SprayCard){const remaining=cards.filter(c=>c.id!==card.id);setCards(remaining);setActiveCardId(remaining[Math.max(0,activeIndex-1)]?.id||remaining[0]?.id||'')}
  function validateReady(activeCards:SprayCard[]){if(!date||!mandor)return{message:'Tanggal dan Mandor wajib diisi.',cardId:activeCards[0]?.id||''};if(!activeCards.length)return{message:'Isi minimal satu Unit Card sebelum disimpan.',cardId:''};const seen=new Set<string>();for(let i=0;i<activeCards.length;i++){const c=activeCards[i];if(!c.unit||!c.noUnit||!c.paddock)return{message:`Unit ${i+1}: lengkapi Jenis Unit, No. Unit, dan Paddock.`,cardId:c.id};const key=`${c.unit}|${c.noUnit}`.toLowerCase();if(seen.has(key))return{message:`Unit ${i+1}: ${c.noUnit} sudah digunakan pada unit lain.`,cardId:c.id};seen.add(key);if(!c.activity||!c.deskripsi||!c.variety||!c.type)return{message:`Unit ${c.noUnit}: lengkapi Activity, Deskripsi, Variety, dan Type.`,cardId:c.id};if(n(c.area)<=0)return{message:`Unit ${c.noUnit}: Luas aktual wajib lebih dari 0.`,cardId:c.id};const timing=timingFor(c);if(!timing.ready)return{message:`Unit ${c.noUnit}: ${timing.error}`,cardId:c.id}}return null}
  function showProblem(problem:{message:string;cardId:string}){if(problem.cardId)setActiveCardId(problem.cardId);setMessage(problem.message);window.setTimeout(()=>document.querySelector('.active-unit-card')?.scrollIntoView({behavior:'smooth',block:'start'}),60)}
  async function saveAll(saveType:'draft'|'ready'){
    const activeCards=cards.filter(hasCardInput),localDraft:SprayDraft={sessionId,date,shift,mandor,assistant,cards,activeCardId}
    if(saveType==='draft'&&!editing)await saveDraft(draftKey,localDraft)
    if(saveType==='ready'){const problem=validateReady(activeCards);if(problem){showProblem(problem);return}}
    const serverCards=saveType==='draft'?activeCards.filter(c=>Boolean(date&&mandor&&c.paddock)):activeCards
    if(saveType==='draft'&&!serverCards.length){setMessage('Draft Spraying tersimpan di perangkat. Isi Tanggal, Mandor, dan Paddock agar Draft juga muncul di Data QC.');return}
    setBusy(true);setMessage('')
    try{
      const records:QcRecord[]=[],savedIds=new Map<string,{recordId:string;saveType:string}>();let queued=0,firestoreFirstCount=0
      for(const card of serverCards){
        const materials=((master.materials||[])as MaterialMaster[]).filter(x=>String(x.description||'').trim()===card.deskripsi&&/^Pesticide\s*[1-4]$/i.test(String(x.slot||'').trim())).sort((a,b)=>String(a.slot).localeCompare(String(b.slot))).slice(0,4)
        const timing=timingFor(card),holdIntervals:HoldInterval[]=await Promise.all(card.holds.map(async({id,file,removePhoto,...hold})=>({...hold,photoBase64:removePhoto?'':file?await photoData(file):text(hold.photoBase64),photoDriveUrl:removePhoto?'':text(hold.photoDriveUrl)})))
        const uploaded=card.saveType==='uploaded',recordId=card.recordId||`qc_${Date.now()}_${Math.random().toString(36).slice(2,8)}`,estimatedAdjuvant=((n(card.adjuvantDosage)*n(card.waterRate)*n(card.area))/1000).toFixed(2)
        const record:QcRecord={id:recordId,sessionId,formType:'spray',date,shift,status:'Working',name:mandor,nameOfAssistan:assistant,startTime:card.startTime,endTime:card.endTime,unit:card.unit,noUnit:card.noUnit,area:card.area,activity:card.activity,deskripsi:card.deskripsi,paddock:card.paddock,variety:card.variety,type:card.type,dropper:card.dropper,nozzle:card.nozzle,dropletSize:card.dropletSize,height:card.height,rowSpacing:card.rowSpacing,speed:card.speed,adjuvant:card.adjuvant,adjuvantDosage:card.adjuvantDosage,actUsageAdjuvant:card.actUsageAdjuvant,waterRate:card.waterRate,waterQuality:card.waterQuality,actualUsage:card.actualUsage,windSpeed:card.windSpeed,temperature:card.temperature,humidity:card.humidity,deltaT:card.deltaT,weatherCondition:card.weatherCondition,noted:card.noted,saveType:uploaded?'uploaded':saveType,inputtedBy:user.username,createdAt:card.createdAt||new Date().toISOString(),clientRevision:crypto.randomUUID(),photoBase64:card.removePhoto?'':card.photo?await photoData(card.photo):'',photoDriveUrl:card.removePhoto?'':card.photoDriveUrl||'',estUsageAdjuvant:estimatedAdjuvant,holdIntervals,workingDurationMinutes:timing.ready?timing.working:0,holdTotalMinutes:timing.ready?timing.total:0,effectiveWorkingMinutes:timing.ready?timing.effective:0}
        for(let i=0;i<4;i++){const item=materials[i];record[`pesticide${i+1}`]=item?.material||'';record[`dosage${i+1}`]=item?.dosage||'';record[`estUsagePesticide${i+1}`]=item?(n(item.dosage)*n(card.area)).toFixed(2):'';record[`actUsagePesticide${i+1}`]=card.actualMaterials[i]||''}
        const result=saveType==='draft'&&!uploaded?await saveDraftFirestoreFirst(token,record):await sendOrQueue(token,uploaded?'finalizeRecord':'syncRecord',record);if(result.queued)queued++;if(result.firestoreFirst)firestoreFirstCount++
        const nextSaveType=result.queued?(uploaded?'upload_queued':saveType==='draft'?'draft_queued':record.saveType):record.saveType
        records.push({...record,saveType:nextSaveType});savedIds.set(card.id,{recordId,saveType:String(nextSaveType)})
      }
      onSaved(records)
      if(saveType==='draft'&&!editingUploaded){if(!editing){const nextCards=cards.map(c=>{const saved=savedIds.get(c.id);return saved?{...c,recordId:saved.recordId,saveType:saved.saveType}:c});setCards(nextCards);await saveDraft(draftKey,{sessionId,date,shift,mandor,assistant,cards:nextCards,activeCardId})}setMessage(queued?`${records.length} unit tersimpan aman; ${queued} menunggu sinkronisasi.`:firestoreFirstCount===records.length?`Draft ${records.length} unit Spraying tersimpan di Firestore; Data QC diperbarui realtime.`:`Draft ${records.length} unit tersimpan; form tetap dipertahankan.`);return}
      await clearDraft(draftKey);setMessage(queued?`${records.length} unit tersimpan aman; ${queued} menunggu sinkronisasi.`:editingUploaded?'Koreksi session Spraying berhasil disimpan.':`${records.length} unit Spraying berhasil disimpan.`)
      if(!editing){const fresh=emptyCard();setCards([fresh]);setActiveCardId(fresh.id);setSessionId(`spraysession_${Date.now()}_${Math.random().toString(36).slice(2,7)}`)}
    }catch(error){setMessage(error instanceof Error?error.message:'Gagal menyimpan sesi Spraying.')}finally{setBusy(false)}
  }

  const card=activeCard
  const activities=card?unique(plans.map(p=>p.activity)):[]
  const descriptions=card?unique(plans.filter(p=>String(p.activity)===card.activity).map(p=>p.description||p.deskripsi)):[]
  const types=card?unique(plans.filter(p=>String(p.activity)===card.activity&&String(p.description||p.deskripsi)===card.deskripsi).map(p=>p.type)):[]
  const candidatePlans=card?plans.filter(p=>String(p.activity)===card.activity&&String(p.description||p.deskripsi)===card.deskripsi&&(!card.type||String(p.type)===card.type)):[]
  const paddocks=unique(candidatePlans.map(p=>p.paddock)),varieties=card?unique(candidatePlans.filter(p=>String(p.paddock)===card.paddock).map(p=>p.variety)):[]
  const numbers=card?unique(card.unit?(master.unitMap?.[card.unit]||[]):[]):[]
  const materials=card?((master.materials||[])as MaterialMaster[]).filter(x=>String(x.description||'').trim()===card.deskripsi&&/^Pesticide\s*[1-4]$/i.test(String(x.slot||'').trim())).sort((a,b)=>String(a.slot).localeCompare(String(b.slot))).slice(0,4):[]
  const timing=card?timingFor(card):{ready:false,total:0,working:0,effective:0,error:''}
  const estimatedAdjuvant=card?((n(card.adjuvantDosage)*n(card.waterRate)*n(card.area))/1000).toFixed(2):'0.00'

  return <section>
    <div className="section-head"><div><div className="eyebrow">SPRAYING DAILY SESSION</div><h2>{editingUploaded?'Koreksi Spraying Uploaded':editing?'Edit Daily Session Spraying':'Input Spraying per Unit'}</h2></div><span className="badge">Unit-centric</span></div>
    <div className="panel session-bar"><label>Tanggal<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>Shift<select value={shift} onChange={e=>setShift(e.target.value)}>{(master.shifts?.length?master.shifts:['1','2']).map(x=><option key={x}>{x}</option>)}</select></label><label>Mandor<select value={mandor} onChange={e=>setMandor(e.target.value)}><option value="">Pilih…</option>{(master.names||[]).map(x=><option key={x}>{x}</option>)}</select></label><label>Asisten<select value={assistant} onChange={e=>setAssistant(e.target.value)}><option value="">Pilih…</option>{(master.assistants||[]).map(x=><option key={x}>{x}</option>)}</select></label></div>
    <div className="unit-tab-shell"><div className="unit-tab-rail" role="tablist" aria-label="Daftar unit spraying">{cards.map((c,i)=><button type="button" role="tab" aria-selected={c.id===card?.id} className={`unit-tab ${c.id===card?.id?'active':''}`} key={c.id} onClick={()=>setActiveCardId(c.id)}><span>UNIT {i+1}</span><strong>{c.noUnit||'Belum dipilih'}</strong><small>{c.paddock||'Paddock -'}</small></button>)}<button type="button" className="unit-tab add-tab" onClick={addUnit}><span>+</span><strong>Tambah Unit</strong><small>Unit baru</small></button></div></div>
    {message&&<div className="alert">{message}</div>}
    {card&&<article className="unit-card active-unit-card"><div className="unit-card-head"><div><div className="eyebrow">UNIT {activeIndex+1} DARI {cards.length}</div><h3>{card.noUnit||'Unit belum dipilih'}</h3><p>{card.paddock||'Paddock -'} • {card.activity||'Activity -'}{card.saveType==='uploaded'?' • Uploaded':card.recordId?' • Draft tersimpan':''}</p></div><div className="row-actions"><button type="button" onClick={()=>duplicateCard(card)}>Duplikat</button>{cards.length>1&&!card.recordId&&<button type="button" className="danger" onClick={()=>removeCard(card)}>Hapus Unit</button>}</div></div>
      <section className="subpanel working-section"><div className="section-head"><div><div className="eyebrow">WORKING</div><h4>Unit & waktu kerja</h4></div><button type="button" onClick={()=>addHold(card.id)}>⏸ Tambah HOLD</button></div><div className="form-grid"><label>Jenis Unit<select value={card.unit} onChange={e=>patchCard(card.id,{unit:e.target.value,noUnit:''})}><option value="">Pilih…</option>{unitTypes.map(x=><option key={x}>{x}</option>)}</select></label><label>No. Unit<select value={card.noUnit} onChange={e=>patchCard(card.id,{noUnit:e.target.value})}><option value="">Pilih…</option>{numbers.map(x=><option key={x}>{x}</option>)}</select></label><label>Luas aktual (Ha)<input type="number" step=".01" min="0" value={card.area} onChange={e=>patchCard(card.id,{area:e.target.value})}/></label><label>Jam mulai<div className="inline-field"><input type="time" value={card.startTime} onChange={e=>patchCard(card.id,{startTime:e.target.value})}/><button type="button" onClick={()=>patchCard(card.id,{startTime:nowTime()})}>Saat ini</button></div></label><label>Jam selesai<div className="inline-field"><input type="time" value={card.endTime} onChange={e=>patchCard(card.id,{endTime:e.target.value})}/><button type="button" onClick={()=>patchCard(card.id,{endTime:nowTime()})}>Saat ini</button></div></label></div>{timing.ready?<div className="stats-grid"><Stat label="Rentang Working" value={durationLabel(timing.working)}/><Stat label="Total HOLD" value={durationLabel(timing.total)}/><Stat label="Working Efektif" value={durationLabel(timing.effective)}/></div>:<div className="alert">{timing.error}</div>}</section>
      <section className="subpanel"><h4>Program & Paddock</h4><fieldset><legend>Activity</legend><Choice values={activities} value={card.activity} onChange={value=>patchCard(card.id,{activity:value,deskripsi:'',paddock:'',variety:'',type:'',actualMaterials:{}})}/></fieldset><fieldset><legend>Deskripsi</legend><Choice values={descriptions} value={card.deskripsi} onChange={value=>{const matchingTypes=unique(plans.filter(p=>String(p.activity)===card.activity&&String(p.description||p.deskripsi)===value).map(p=>p.type));patchCard(card.id,{deskripsi:value,paddock:'',variety:'',type:matchingTypes.length===1?matchingTypes[0]:'',actualMaterials:{}})}}/></fieldset><fieldset><legend>Type</legend><Choice values={types} value={card.type} onChange={value=>patchCard(card.id,{type:value,paddock:'',variety:''})}/></fieldset><fieldset><legend>Paddock</legend><Choice values={paddocks} value={card.paddock} onChange={value=>{const vars=unique(candidatePlans.filter(p=>String(p.paddock)===value).map(p=>p.variety));patchCard(card.id,{paddock:value,variety:vars.length===1?vars[0]:''})}}/></fieldset><fieldset><legend>Variety</legend><Choice values={varieties} value={card.variety} onChange={value=>patchCard(card.id,{variety:value})}/></fieldset></section>
      <section className="subpanel"><h4>Setting Sprayer</h4><div className="form-grid"><fieldset><legend>Dropper</legend><Choice values={master.dropper?.length?master.dropper:['Yes','No']} value={card.dropper} onChange={value=>patchCard(card.id,{dropper:value})}/></fieldset><fieldset className="span-2"><legend>Nozzle</legend><Choice values={master.nozzles||[]} value={card.nozzle} onChange={value=>patchCard(card.id,{nozzle:value})}/></fieldset><label>Droplet Size (µm)<input type="number" value={card.dropletSize} onChange={e=>patchCard(card.id,{dropletSize:e.target.value})}/></label><label>Height (m)<input type="number" step=".01" value={card.height} onChange={e=>patchCard(card.id,{height:e.target.value})}/></label><label>Row Spacing (m)<input type="number" step=".01" value={card.rowSpacing} onChange={e=>patchCard(card.id,{rowSpacing:e.target.value})}/></label><label>Speed (km/jam)<input type="number" step=".01" value={card.speed} onChange={e=>patchCard(card.id,{speed:e.target.value})}/></label></div></section>
      <section className="subpanel"><h4>Bahan Kimia Otomatis</h4><p className="muted">Estimated Usage = Dosis/Ha × Luas aktual unit.</p><div className="material-grid">{materials.length?materials.map((item,i)=><article className="material-card" key={`${item.slot}-${i}`}><strong>{item.slot}<br/>{item.material} <small>({item.unit||'-'})</small></strong><label>Dosis/Ha<input readOnly value={String(item.dosage||'')}/></label><label>Estimated Usage<input readOnly value={(n(item.dosage)*n(card.area)).toFixed(2)}/></label><label>Actual Used<input type="number" step=".001" value={card.actualMaterials[i]||''} onChange={e=>patchCard(card.id,{actualMaterials:{...card.actualMaterials,[i]:e.target.value}})}/></label></article>):<p className="muted">Pilih Deskripsi untuk memuat Pesticide 1–4.</p>}</div></section>
      <section className="subpanel"><h4>Adjuvant & Kondisi Lapangan</h4><div className="form-grid"><label>Nama adjuvant<input list={`adjuvants-${card.id}`} value={card.adjuvant} onChange={e=>patchCard(card.id,{adjuvant:e.target.value})}/><datalist id={`adjuvants-${card.id}`}>{adjuvants.map(x=><option value={x} key={x}/>)}</datalist></label><label>Dosis Adjuvant (mL/L)<input type="number" step=".01" value={card.adjuvantDosage} onChange={e=>patchCard(card.id,{adjuvantDosage:e.target.value})}/></label><label>Estimated Adjuvant (L)<input readOnly value={estimatedAdjuvant}/></label><label>Actual Adjuvant (L)<input type="number" step=".01" value={card.actUsageAdjuvant} onChange={e=>patchCard(card.id,{actUsageAdjuvant:e.target.value})}/></label><label>Water Rate (L/Ha)<input type="number" step=".01" value={card.waterRate} onChange={e=>patchCard(card.id,{waterRate:e.target.value})}/></label><fieldset className="span-2"><legend>Water Quality</legend><Choice values={master.waterQualities||[]} value={card.waterQuality} onChange={value=>patchCard(card.id,{waterQuality:value})}/></fieldset><label>Actual Usage Air (L)<input type="number" step=".01" value={card.actualUsage} onChange={e=>patchCard(card.id,{actualUsage:e.target.value})}/></label><label>Wind Speed (km/jam)<input type="number" step=".01" value={card.windSpeed} onChange={e=>patchCard(card.id,{windSpeed:e.target.value})}/></label><label>Temperature (°C)<input type="number" step=".01" value={card.temperature} onChange={e=>patchCard(card.id,{temperature:e.target.value})}/></label><label>Humidity (%)<input type="number" step=".01" value={card.humidity} onChange={e=>patchCard(card.id,{humidity:e.target.value})}/></label><label>Delta T (°C)<input type="number" step=".01" value={card.deltaT} onChange={e=>patchCard(card.id,{deltaT:e.target.value})}/></label><fieldset className="span-2"><legend>Weather Condition</legend><Choice values={master.weatherConditions||[]} value={card.weatherCondition} onChange={value=>patchCard(card.id,{weatherCondition:value})}/></fieldset></div></section>
      <section className="subpanel spray-hold-section"><div className="section-head"><div><div className="eyebrow">HOLD • ISSUE / DOWNTIME</div><h4>Waktu unit berhenti</h4></div><button type="button" onClick={()=>addHold(card.id)}>+ Tambah HOLD</button></div>{!card.holds.length&&<div className="empty compact-empty">Tidak ada HOLD.</div>}{card.holds.map((hold,i)=><div className="hold-card" key={hold.id}><div className="hold-card-title"><strong>HOLD {i+1}</strong><button type="button" className="danger" onClick={()=>patchCard(card.id,{holds:card.holds.filter(h=>h.id!==hold.id)})}>Hapus</button></div><div className="hold-row-react"><label>Mulai<input type="time" value={hold.start} onChange={e=>patchHold(card.id,hold.id,{start:e.target.value})}/></label><label>Selesai<input type="time" value={hold.end} onChange={e=>patchHold(card.id,hold.id,{end:e.target.value})}/></label><label>Alasan<input placeholder="Contoh: angin kencang" value={hold.reason} onChange={e=>patchHold(card.id,hold.id,{reason:e.target.value})}/></label><label>Angin (km/jam)<input type="number" step=".1" value={hold.windSpeed} onChange={e=>patchHold(card.id,hold.id,{windSpeed:e.target.value})}/></label><PhotoPicker compact onFile={file=>patchHold(card.id,hold.id,{file,removePhoto:file?false:hold.removePhoto})} onRemove={()=>patchHold(card.id,hold.id,{file:undefined,removePhoto:true})} selectedName={hold.file?.name} existing={!hold.removePhoto&&Boolean(hold.photoDriveUrl)} removed={hold.removePhoto}/></div></div>)}</section>
      <section className="subpanel"><h4>Foto & Catatan Unit</h4><PhotoPicker onFile={file=>patchCard(card.id,{photo:file,removePhoto:file?false:card.removePhoto})} onRemove={()=>patchCard(card.id,{photo:undefined,removePhoto:true})} selectedName={card.photo?.name} existing={!card.removePhoto&&Boolean(card.photoDriveUrl)} removed={card.removePhoto}/><label>Catatan<textarea rows={3} value={card.noted} onChange={e=>patchCard(card.id,{noted:e.target.value})}/></label></section>
      <div className="unit-summary"><span>Luas Aktual<strong>{n(card.area).toLocaleString('id-ID')} Ha</strong></span><span>Actual Air<strong>{n(card.actualUsage).toLocaleString('id-ID')} L</strong></span><span>Working Efektif<strong>{timing.ready?durationLabel(timing.effective):'-'}</strong></span></div>
    </article>}
    <div className="panel session-summary"><div><span>Jumlah unit</span><strong>{total.units}</strong></div><div><span>Total luas aktual</span><strong>{total.area.toLocaleString('id-ID')} Ha</strong></div><div><span>Total actual air</span><strong>{total.water.toLocaleString('id-ID')} L</strong></div></div>
    <div className="form-actions">{editing&&<button type="button" disabled={busy} onClick={onCancelEdit}>Batal Edit</button>}{!editingUploaded&&<button type="button" disabled={busy} onClick={()=>void saveAll('draft')}>{editing?'Perbarui Draft Session':'Simpan Draft Semua Unit'}</button>}<button className="primary" type="button" disabled={busy} onClick={()=>void saveAll('ready')}>{busy?'Menyimpan…':editingUploaded?'Simpan Koreksi Uploaded':editing?'Perbarui Session Siap Upload':'Simpan Semua Unit'}</button></div>
  </section>
}
function Stat({label,value}:{label:string;value:string}){return <div className="stat"><span>{label}</span><strong>{value}</strong></div>}
